### ISSUE TITLE
Create Classes

### ISSUE THREAD

**Issue by KryoKorpz** [Lambda-School-Labs/LabsPT1_knowledge_rocket#102]
Option to view/update students ---> update student page
some of the rocket names don't scale well I think if they are too big. (text runs off box)

- [ ] view/update students
- [ ] scale rocket names to match container

**Comment by ravb2019** [comment]
https://github.com/Lambda-School-Labs/LabsPT1_knowledge_rocket/pull/114

**Comment by KryoKorpz** [comment]
![screenshot 75](https://user-images.githubusercontent.com/31119775/52819249-af246300-305d-11e9-88fa-45e355e0da98.png)
![screenshot 76](https://user-images.githubusercontent.com/31119775/52819252-af246300-305d-11e9-9704-de50e5e8300d.png)

some minor problems with long user names at a few breakpoint's but overall much better.
maybe we can change it to only show like the first few characters of a rocket name?
