### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by holly-g** [Lambda-School-Labs/LabsPT1_knowledge_rocket#106]
- [x] Add section for installation. (E.g. Instructions on what to run from the command line for frontend and backend, environment variables, etc.)
- [x] Add one or two lines to describe the frontend/backend dependencies
- [x] Describe what the app is trying to solve 
- [x]  A mapping of the endpoints for how to interact with the API is present in the docs
- [x] Write the documentation in clear and concise language so that any one can run the application from their local machine. Don't forget about `pip freeze > requirements.txt`

**Comment by KryoKorpz** [comment]
https://github.com/Lambda-School-Labs/LabsPT1_knowledge_rocket/pull/121#issue-253327504
