### ISSUE TITLE
No redirect when rocket is created or email sent

### ISSUE THREAD

**Issue by LisaCee** [Lambda-School-Labs/LabsPT1_knowledge_rocket#118]

**Comment by LisaCee** [comment]
- [ ] Have successful rocket creation redirect to Rockets

- [ ] Have email successfully sent redirect to Welcome page

**Comment by KryoKorpz** [comment]
https://github.com/Lambda-School-Labs/LabsPT1_knowledge_rocket/pull/119#issue-253300087
