### ISSUE TITLE
Classes Display Page ---> Class buttons

### ISSUE THREAD

**Issue by KryoKorpz** [Lambda-School-Labs/LabsPT1_knowledge_rocket#138]
Only the text on the button is a link, need to make whole button a link, rather than just the text

**Comment by LisaCee** [comment]
![ClassButton](https://user-images.githubusercontent.com/18077352/55188362-75647300-5158-11e9-8612-6fe467e991bf.JPG)

Is it these buttons you are describing?  We want the whole white area to be clickable, rather than just the text?

**Comment by LisaCee** [comment]
If so, I can get this one done tonight.

**Comment by KryoKorpz** [comment]
Yes; either have the whole button the link; or remove the hover. It's misleading when the whole button hovers but only the text is the link :)

**Comment by LisaCee** [comment]
Got it.  I will get this done tonight.

**Comment by LisaCee** [comment]
PR submitted
https://github.com/Lambda-School-Labs/LabsPT1_knowledge_rocket/pull/140/files#
