### ISSUE TITLE
Bug: Duplicate GetUser

### ISSUE THREAD

**Issue by holly-g** [Lambda-School-Labs/LabsPT1_knowledge_rocket#53]
![screenshot 2019-01-19 at 3 39 55 pm](https://user-images.githubusercontent.com/26711083/51432125-847ef000-1c00-11e9-9a1f-01b3fe2aad8a.png)

**Comment by LisaCee** [comment]
I think if you look in index.js, you'll see in router we have a duplicate.

**Comment by ravb2019** [comment]
Bug is Fixed. I have created pull request. @holly-g how should we move this bug?

**Comment by holly-g** [comment]
I've referenced this issue in your PR. 
I'll close it once we get it approved/merged.
